### ISSUE TITLE
Needs Adjustments for PHP 7.4 and Above

### ISSUE THREAD

**Issue by golanorbi** [d6lts/imageapi#1]
Hi,

This module needs some adjustments to work with PHP 7.4 and above.
I've fixed the following error in my environment.

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/360.innosec.co.il/public_html/sites/all/modules/imageapi/imageapi.module on line 431

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/360.innosec.co.il/public_html/sites/all/modules/imageapi/imageapi.module on line 432

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/360.innosec.co.il/public_html/sites/all/modules/imageapi/imageapi.module on line 433

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/360.innosec.co.il/public_html/sites/all/modules/imageapi/imageapi.module on line 447

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/360.innosec.co.il/public_html/sites/all/modules/imageapi/imageapi.module on line 448

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/360.innosec.co.il/public_html/sites/all/modules/imageapi/imageapi.module on line 449

Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/360.innosec.co.il/public_html/sites/all/modules/imageapi/imageapi.module on line 450

**Comment by dsnopek** [comment]
The curly braces should all have been fixed a while ago:

https://github.com/d6lts/imageapi/blob/6.x-1.x/imageapi.module#L431

What version are you using?

**Comment by golanorbi** [comment]
It hasn't been fixed in the latest version ImageAPI 6.x-1.11.

**Comment by dsnopek** [comment]
Hm, there should be a 1.12 release (we tagged it!) but for some reason there isn't actually a release object on GitHub. I'll see about fixing that...

**Comment by dsnopek** [comment]
Release created https://github.com/d6lts/imageapi/releases/tag/6.x-1.12
